### ISSUE TITLE
Issue with app.css and app.map

### ISSUE THREAD

**Issue by djrobby** [zkayser/phoenix-elm-template#1]
https://github.com/zkayser/phoenix-elm-template/blob/ba1314038c69d50c6584bf75c5aa29ee543d7e7f/config/dev.exs#L20

Following your suggestions, yields the **app.css** and the **app.map** files inside the **priv/static/js** directory and I am thinking this line is the cause. Can you advise a fix?

**Comment by zkayser** [comment]
@djrobby Thanks for pointing that out. I wasn't paying much attention to what was going on with the CSS assets.

At any rate, I changed the `watch script` in `/assets/package.json` and just changed the watchers config in `dev.exs` to run the npm script from the assets directory.

https://github.com/zkayser/phoenix-elm-template/blob/e922e831464fbdfce3e06a06aa6b96a4a73cf441/config/dev.exs#L14-L19

https://github.com/zkayser/phoenix-elm-template/blob/e922e831464fbdfce3e06a06aa6b96a4a73cf441/assets/package.json#L4-L7

That should fix the issue.

**Comment by djrobby** [comment]
@zkayser thank you! much appreciated.
